product/urls.py
from django.urls import path
from .views import*

app_name = "product"

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('product/', ProductView.as_view(), name='product'),
    path('category/<int:pk>/',
         CategoryDetailView.as_view(), name='categorydetail'),
    path('kitchen/', KitchenView.as_view(), name="kitchen"),
    path('product/<int:pk>/details/',
         ProductDetailsView.as_view(), name="details"),
    path('product/create/', ProductCreateView.as_view(), name="create"),
    path('search/', SearchView.as_view(), name="search"),
    path('restric/', RestricView.as_view(), name="restric"),
    path('firm-admin/', FormAdminView.as_view(), name="adminhome"),
    path('firm-admin/product/list/',
         AdminProductListView.as_view(), name="adminproductlist"),
    path('firm-admin/product/add/',
         AdminProductAddView.as_view(), name="adminproductadd"),
    path('firm-admin/product/<int:pk>/create/',
         AdminProductUpdateView.as_view(), name="adminproductupdate"),
    path('firm-admin/product/<int:pk>/delete/',
         AdminProductDeleteView.as_view(), name="adminproductdelete"),
    path('firm-admin/category/list/',
         AdminCategoryListView.as_view(), name="admincategorylist"),
    path('firm-admin/category/add/',
         AdminCategoryAddView.as_view(), name="admincategoryadd"),
    path('firm-admin/category/<int:pk>/update/',
         AdminCategoryUpdateView.as_view(), name="admincategoryupdate"),
]
    

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("product.urls"))
]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/admincategoryadd.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}

{% block contnet %}

<div class="table-agile-info">
<div class="panel panel-default">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button class="btn btn-info w-100">submit</button>
</form>


{% endblock %}

templates/admintemplates/admincategorylist.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}

{% block contnet %}

<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     Basic table
    </div>
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'align="center">
        <thead>
          <tr>
            <th data-breakpoints="xs">ID</th>
            <th>Category Name</th>
            <th>Images</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        	{% for i in categoryobjectt %}
            <tr data-expanded="true">
               <td>{{forloop.counter}}</td>
               <td>{{i.title}}</td>
               <td><img src="{{i.image.url}}" width="100"></td>
               <td>
                 <a href="{% url 'product:admincategoryupdate' i.pk %}" class="adminproductupdatebtn btn-primary">Update</a>
                 <a href="{% url 'product:adminproductdelete' i.pk %}" class="btn btn-danger">Delete</a>

               </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>



{% endblock %}

templates/admintemplates/admincategoryupdate.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}

{% block contnet %}

<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     Basic table
    </div>
    <table class="table" ui-jq="footable" ui-options='{
      "paging": {
        "enabled": true
      },
      "filtering": {
        "enabled": true
      },
      "sorting": {
        "enabled": true
      }}'align="center">
					<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{form.as_p}}
						<button class="btn btn-info w-100">Save Data</button>
					</form>
  </table>
  </div>
</div>



{% endblock %}

templates/admintemplates/adminhome.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}

{% block contnet %}

		<div class="row">
			<div class="panel-body">
				<div class="col-md-12 w3ls-graph">
					<!--agileinfo-grap-->
						<div class="agileinfo-grap">
							<div class="agileits-box">
								<header class="agileits-box-header clearfix">
									<h3>Visitor Statistics</h3>
										<div class="toolbar">
											
											
										</div>
								</header>
								<div class="agileits-box-body clearfix">
									<div id="hero-area"></div>
								</div>
							</div>
						</div>
	<!--//agileinfo-grap-->

				</div>
			</div>
		</div>
		<div class="agil-info-calendar">
		<!-- calendar -->
		<div class="col-md-6 agile-calendar">
			<div class="calendar-widget">
                <div class="panel-heading ui-sortable-handle">
					<span class="panel-icon">
                      <i class="fa fa-calendar-o"></i>
                    </span>
                    <span class="panel-title"> Calendar Widget</span>
                </div>
				<!-- grids -->
					<div class="agile-calendar-grid">
						<div class="page">
							
							<div class="w3l-calendar-left">
								<div class="calendar-heading">
									
								</div>
								<div class="monthly" id="mycalendar"></div>
							</div>
							
							<div class="clearfix"> </div>
						</div>
					</div>
			</div>
		</div>
		<!-- //calendar -->
		<div class="col-md-6 w3agile-notifications">
			<div class="notifications">
				<!--notification start-->
				
					<header class="panel-heading">
						Notification 
					</header>
					<div class="notify-w3ls">
						<div class="alert alert-info clearfix">
							<span class="alert-icon"><i class="fa fa-envelope-o"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender"><span><a href="#">Jonathan Smith</a></span> send you a mail </li>
									<li class="pull-right notification-time">1 min ago</li>
								</ul>
								<p>
									Urgent meeting for next proposal
								</p>
							</div>
						</div>
						<div class="alert alert-danger">
							<span class="alert-icon"><i class="fa fa-facebook"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender"><span><a href="#">Jonathan Smith</a></span> mentioned you in a post </li>
									<li class="pull-right notification-time">7 Hours Ago</li>
								</ul>
								<p>
									Very cool photo jack
								</p>
							</div>
						</div>
						<div class="alert alert-success ">
							<span class="alert-icon"><i class="fa fa-comments-o"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender">You have 5 message unread</li>
									<li class="pull-right notification-time">1 min ago</li>
								</ul>
								<p>
									<a href="#">Anjelina Mewlo, Jack Flip</a> and <a href="#">3 others</a>
								</p>
							</div>
						</div>
						<div class="alert alert-warning ">
							<span class="alert-icon"><i class="fa fa-bell-o"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender">Domain Renew Deadline 7 days ahead</li>
									<li class="pull-right notification-time">5 Days Ago</li>
								</ul>
								<p>
									Next 5 July Thursday is the last day
								</p>
							</div>
						</div>
						<div class="alert alert-info clearfix">
							<span class="alert-icon"><i class="fa fa-envelope-o"></i></span>
							<div class="notification-info">
								<ul class="clearfix notification-meta">
									<li class="pull-left notification-sender"><span><a href="#">Jonathan Smith</a></span> send you a mail </li>
									<li class="pull-right notification-time">1 min ago</li>
								</ul>
								<p>
									Urgent meeting for next proposal
								</p>
							</div>
						</div>
						
					</div>
				
				<!--notification end-->
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
			<!-- tasks -->
			<div class="agile-last-grids">
				<div class="col-md-4 agile-last-left">
					<div class="agile-last-grid">
						<div class="area-grids-heading">
							<h3>Monthly</h3>
						</div>
						<div id="graph7"></div>
						<script>
						// This crosses a DST boundary in the UK.
						Morris.Area({
						  element: 'graph7',
						  data: [
							{x: '2013-03-30 22:00:00', y: 3, z: 3},
							{x: '2013-03-31 00:00:00', y: 2, z: 0},
							{x: '2013-03-31 02:00:00', y: 0, z: 2},
							{x: '2013-03-31 04:00:00', y: 4, z: 4}
						  ],
						  xkey: 'x',
						  ykeys: ['y', 'z'],
						  labels: ['Y', 'Z']
						});
						</script>

					</div>
				</div>
				<div class="col-md-4 agile-last-left agile-last-middle">
					<div class="agile-last-grid">
						<div class="area-grids-heading">
							<h3>Daily</h3>
						</div>
						<div id="graph8"></div>
						<script>
						/* data stolen from http://howmanyleft.co.uk/vehicle/jaguar_'e'_type */
						var day_data = [
						  {"period": "2016-10-01", "licensed": 3407, "sorned": 660},
						  {"period": "2016-09-30", "licensed": 3351, "sorned": 629},
						  {"period": "2016-09-29", "licensed": 3269, "sorned": 618},
						  {"period": "2016-09-20", "licensed": 3246, "sorned": 661},
						  {"period": "2016-09-19", "licensed": 3257, "sorned": 667},
						  {"period": "2016-09-18", "licensed": 3248, "sorned": 627},
						  {"period": "2016-09-17", "licensed": 3171, "sorned": 660},
						  {"period": "2016-09-16", "licensed": 3171, "sorned": 676},
						  {"period": "2016-09-15", "licensed": 3201, "sorned": 656},
						  {"period": "2016-09-10", "licensed": 3215, "sorned": 622}
						];
						Morris.Bar({
						  element: 'graph8',
						  data: day_data,
						  xkey: 'period',
						  ykeys: ['licensed', 'sorned'],
						  labels: ['Licensed', 'SORN'],
						  xLabelAngle: 60
						});
						</script>
					</div>
				</div>
				<div class="col-md-4 agile-last-left agile-last-right">
					<div class="agile-last-grid">
						<div class="area-grids-heading">
							<h3>Yearly</h3>
						</div>
						<div id="graph9"></div>
						<script>
						var day_data = [
						  {"elapsed": "I", "value": 34},
						  {"elapsed": "II", "value": 24},
						  {"elapsed": "III", "value": 3},
						  {"elapsed": "IV", "value": 12},
						  {"elapsed": "V", "value": 13},
						  {"elapsed": "VI", "value": 22},
						  {"elapsed": "VII", "value": 5},
						  {"elapsed": "VIII", "value": 26},
						  {"elapsed": "IX", "value": 12},
						  {"elapsed": "X", "value": 19}
						];
						Morris.Line({
						  element: 'graph9',
						  data: day_data,
						  xkey: 'elapsed',
						  ykeys: ['value'],
						  labels: ['value'],
						  parseTime: false
						});
						</script>

					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		<!-- //tasks -->
		<div class="agileits-w3layouts-stats">
					<div class="col-md-4 stats-info widget">
						<div class="stats-info-agileits">
							<div class="stats-title">
								<h4 class="title">Browser Stats</h4>
							</div>
							<div class="stats-body">
								<ul class="list-unstyled">
									<li>GoogleChrome <span class="pull-right">85%</span>  
										<div class="progress progress-striped active progress-right">
											<div class="bar green" style="width:85%;"></div> 
										</div>
									</li>
									<li>Firefox <span class="pull-right">35%</span>  
										<div class="progress progress-striped active progress-right">
											<div class="bar yellow" style="width:35%;"></div>
										</div>
									</li>
									<li>Internet Explorer <span class="pull-right">78%</span>  
										<div class="progress progress-striped active progress-right">
											<div class="bar red" style="width:78%;"></div>
										</div>
									</li>
									<li>Safari <span class="pull-right">50%</span>  
										<div class="progress progress-striped active progress-right">
											<div class="bar blue" style="width:50%;"></div>
										</div>
									</li>
									<li>Opera <span class="pull-right">80%</span>  
										<div class="progress progress-striped active progress-right">
											<div class="bar light-blue" style="width:80%;"></div>
										</div>
									</li>
									<li class="last">Others <span class="pull-right">60%</span>  
										<div class="progress progress-striped active progress-right">
											<div class="bar orange" style="width:60%;"></div>
										</div>
									</li> 
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-8 stats-info stats-last widget-shadow">
						<div class="stats-last-agile">
							<table class="table stats-table ">
								<thead>
									<tr>
										<th>S.NO</th>
										<th>PRODUCT</th>
										<th>STATUS</th>
										<th>PROGRESS</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<th scope="row">1</th>
										<td>Lorem ipsum</td>
										<td><span class="label label-success">In progress</span></td>
										<td><h5>85% <i class="fa fa-level-up"></i></h5></td>
									</tr>
									<tr>
										<th scope="row">2</th>
										<td>Aliquam</td>
										<td><span class="label label-warning">New</span></td>
										<td><h5>35% <i class="fa fa-level-up"></i></h5></td>
									</tr>
									<tr>
										<th scope="row">3</th>
										<td>Lorem ipsum</td>
										<td><span class="label label-danger">Overdue</span></td>
										<td><h5 class="down">40% <i class="fa fa-level-down"></i></h5></td>
									</tr>
									<tr>
										<th scope="row">4</th>
										<td>Aliquam</td>
										<td><span class="label label-info">Out of stock</span></td>
										<td><h5>100% <i class="fa fa-level-up"></i></h5></td>
									</tr>
									<tr>
										<th scope="row">5</th>
										<td>Lorem ipsum</td>
										<td><span class="label label-success">In progress</span></td>
										<td><h5 class="down">10% <i class="fa fa-level-down"></i></h5></td>
									</tr>
									<tr>
										<th scope="row">6</th>
										<td>Aliquam</td>
										<td><span class="label label-warning">New</span></td>
										<td><h5>38% <i class="fa fa-level-up"></i></h5></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
</section>


{% endblock %}

templates/admintemplates/adminproductdelete.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}

{% block contnet %}

<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     Basic table
    </div>
    <table class="table1" ui-jq="footable" ui-options='{
      "paging": {
        "enabled": true
      },
      "filtering": {
        "enabled": true
      },
      "sorting": {
        "enabled": true
      }}'align="center">
					<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						<button class="btn btn-danger">Delete</button>
					</form>
  </table>
  </div>
</div>



{% endblock %}

templates/admintemplates/adminupdate.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}

{% block contnet %}

<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     Basic table
    </div>
    <table class="table" ui-jq="footable" ui-options='{
      "paging": {
        "enabled": true
      },
      "filtering": {
        "enabled": true
      },
      "sorting": {
        "enabled": true
      }}'align="center">
					<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{{form.as_p}}
						<button class="btn btn-info w-100">Save Data</button>
					</form>
  </table>
  </div>
</div>



{% endblock %}

templates/admintemplates/productcreate.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}

{% block contnet %}

<div class="table-agile-info">
<div class="panel panel-default">
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button class="btn btn-info w-100">submit</button>
</form>


{% endblock %}

templates/admintemplates/productlist.html
{% extends "admintemplates/adminbase.html" %}
{% load static %}

{% block contnet %}

<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     Basic table
    </div>
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'align="center">
        <thead>
          <tr>
            <th data-breakpoints="xs">ID</th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Images</th>
            <th>Quantity</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        	{% for i in productlist %}
            <tr data-expanded="true">
               <td>{{forloop.counter}}</td>
               <td>{{i.name}}</td>
               <td>{{ i.price}}</td>
               <td><img src="{{i.images.url}}" width="100"></td>
               <td>{{i.quentity}}</td>
               <td>
                 <a href="{% url 'product:adminproductupdate' i.pk %}" class="btn btn-primary">Update</a>
                 <a href="{% url 'product:adminproductdelete' i.pk %}" class="btn btn-danger">Delete</a>

               </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>



{% endblock %}