product/urls.py
from django.urls import path
from .views import*

app_name = "product"

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('product/', ProductView.as_view(), name='product'),
    path('category/<int:pk>/',
         CategoryDetailView.as_view(), name='categorydetail'),
    path('kitchen/', KitchenView.as_view(), name="kitchen"),
    path('product/<int:pk>/details/',
         ProductDetailsView.as_view(), name="details"),
    path('product/create/', ProductCreateView.as_view(), name="create"),
    path('search/', SearchView.as_view(), name="search"),
    path('restric/', RestricView.as_view(), name="restric"),
    path('firm-admin/', FormAdminView.as_view(), name="adminhome"),
    path('firm-admin/product/list/',
         AdminProductListView.as_view(), name="adminproductlist"),
    path('firm-admin/product/add/',
         AdminProductAddView.as_view(), name="adminproductadd"),
    path('firm-admin/product/<int:pk>/create/',
         AdminProductUpdateView.as_view(), name="adminproductupdate"),
    path('firm-admin/product/<int:pk>/delete/',
         AdminProductDeleteView.as_view(), name="adminproductdelete"),
    path('firm-admin/category/list/',
         AdminCategoryListView.as_view(), name="admincategorylist"),
    path('firm-admin/category/add/',
         AdminCategoryAddView.as_view(), name="admincategoryadd"),
    path('firm-admin/category/<int:pk>/update/',
         AdminCategoryUpdateView.as_view(), name="admincategoryupdate"),
]
    

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("product.urls"))
]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="category")

    def __str__(self):
        return self.title


class Sub_Category(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.title


class Quentity(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Product(models.Model):
    name = models.CharField(max_length=200)
    images = models.ImageField(upload_to='product', null=True, blank=True)
    price = models.DecimalField(decimal_places=3, max_digits=19)
    category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE)
    weight = models.DecimalField(decimal_places=3, max_digits=19)
    quentity = models.ForeignKey(Quentity, on_delete=models.CASCADE)
    #sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE)
    view_count = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.name

product/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import*


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title', 'image']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter name'
            }),
            'images': forms.ClearableFileInput(attrs={
                'class': 'form-control mb-3',
            }), }


class Sub_CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Sub_Category
        fields = ['title', 'category']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter name'
            }),
            'category': forms.TextInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter category'
            }), }


class QuentityCreateForm(forms.ModelForm):
    class Meta:
        model = Quentity
        fields = ['title']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter name'
            }),
        }


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'images', 'price', 'category', 'weight', 'quentity']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter name'
            }),
            'images': forms.ClearableFileInput(attrs={
                'class': 'form-control mb-3',
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter the price'
            }),
            'category': forms.Select(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter category'
            }),
            'weight': forms.NumberInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter weight'
            }),
            'quentity': forms.NumberInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': 'enter quentity'
            }),
        }
        
class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput())
    password=forms.CharField(widget=forms.PasswordInput())

product/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views.generic import*
from .models import*
from .forms import*
from django.db.models import Q


class BaseMixin(object):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorylist'] = Category.objects.all()
        return context


class Home(BaseMixin, TemplateView):
    template_name = "home.html"


class AboutView(BaseMixin, TemplateView):
    template_name = "about.html"


class LoginView(BaseMixin, TemplateView):
    template_name = "login.html"
# Create your views here.


class ProductView(BaseMixin, TemplateView):
    template_name = "product.html"


class ProductCreateView(CreateView):
    template_name = "create.html"
    form_class = ProductCreateForm
    success_url = "/"


class CategoryDetailView(BaseMixin, DetailView):
    template_name = "households.html"
    model = Category
    context_object_name = "categoryobject"


class KitchenView(TemplateView):
    template_name = "kitchen.html"


class ProductDetailsView(DetailView):
    template_name = "vegitable.html"
    # template_name = "admintemplates/adminbase.html"
    model = Product
    context_object_name = "product_detail"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object
        post.view_count += 1
        post.save()
        return context


class SearchView(TemplateView):
    template_name = "search.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # query = self.request.GET["keyi"]
        query = self.request.GET.get('keyi')
        results = Product.objects.filter(
            Q(name__icontains=query) | Q(category__title__icontains=query))

        context["search_results"] = results
        return context
    # def post(self, request):
    #     query = request.POST.get('keyi')
    #     results = Product.objects.filter(
    #         Q(name__icontains=query) | Q(category__title__icontains=query))
    #     return render(request, self.template_name, {'search_results': results})


class SingleView(TemplateView):
    template_name = "single.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['port'] = Product.objects.all(Q())
        return context


class RestricView(TemplateView):
    template_name = "create.html"

    def dispatch(self, request, *args, **kwargs):
        usr = request.user
        if usr.is_authenticated:
            pass
        else:
            return redirect('/login/')
        return super().dispatch(request, *args, **kwargs)


class FormAdminView(TemplateView):
    template_name = 'admintemplates/adminhome.html'


class AdminProductListView(ListView):
    template_name = "admintemplates/productlist.html"
    queryset = Product.objects.all()
    context_object_name = "productlist"


class AdminProductAddView(CreateView):
    template_name = "admintemplates/productcreate.html"
    form_class = ProductCreateForm
    success_url = '/firm-admin/product/list/'


class AdminProductUpdateView(UpdateView):
    template_name = "admintemplates/adminupdate.html"
    form_class = ProductCreateForm
    model = Product
    success_url = '/firm-admin/product/list/'


class AdminProductDeleteView(DeleteView):
    template_name = "admintemplates/adminproductdelete.html"
    model = Product
    success_url = '/firm-admin/product/list/'


class AdminCategoryListView(ListView):
    template_name = "admintemplates/admincategorylist.html"
    queryset = Category.objects.all()
    context_object_name = "categoryobjectt"


class AdminCategoryAddView(CreateView):
    template_name = "admintemplates/admincategoryadd.html"
    form_class = CategoryForm
    success_url = "/firm-admin/category/list/"


class AdminCategoryUpdateView(UpdateView):
    template_name = "admintemplates/admincategoryupdate.html"
    form_class = CategoryForm
    model = Category
    success_url = "/firm-admin/category/list/"


class LoginView(FormView):
    template_name = "login.html"
    form_class = LoginForm
    success_url = "/firm-admin/"

    def form_valid(self, form):
        a = form.cleaned_data['username']
        b = form.cleaned_data.get('password')
        usr = authenticate(username=a, password=b)
        if usr is not None:
            login(self.request, usr)
        else:
            return render(self.request, self.template_name,
                          {"error": "invalid creditentials", 'form': form})

        return super().form_valid(form)


class LogoutView(View):
    def get(self,request):
        logout(request)
        return redirect("/")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Grocery Store a Ecommerce Online Shopping Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Grocery Store Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!-- font-awesome icons -->
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" type="text/css" media="all" /> 
<!-- //font-awesome icons -->
<!-- js -->
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<!-- //js -->
<link href='//fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!-- start-smoth-scrolling -->
</head>
	
<body>
<!-- header -->
	<div class="agileits_header">
		<div class="w3l_offers">
			<a href="products.html">Today's special Offers !</a>
		</div>
		<div class="w3l_search">
			<form method="GET"  action ="{% url 'product:search' %}">
				<input type="text" name="keyi" placeholder="serch here">
				<input type="submit" value="">
			</form>
		</div>
		<div class="product_list_header">  
			<form action="#" method="post" class="last">
                <fieldset>
                    <input type="hidden" name="cmd" value="_cart" />
                    <input type="hidden" name="display" value="1" />
                    <input type="submit" name="submit" value="View your cart" class="button" />
                </fieldset>
            </form>
		</div>
		<div class="w3l_header_right">
			<ul>
				<li class="dropdown profile_details_drop">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i><span class="caret"></span></a>
					<div class="mega-dropdown-menu">
						<div class="w3ls_vegetables">
							<ul class="dropdown-menu drp-mnu">
								<li><a href="{% url 'product:login' %}">Login</a></li> 
								<li><a href="login.html">Sign Up</a></li>
							</ul>
						</div>                  
					</div>	
				</li>
			</ul>
		</div>
		<div class="w3l_header_right1">
			<h2><a href="mail.html">Contact Us</a></h2>
		</div>
		<div class="clearfix"> </div>
	</div>
<!-- script-for sticky-nav -->
	<script>
	$(document).ready(function() {
		 var navoffeset=$(".agileits_header").offset().top;
		 $(window).scroll(function(){
			var scrollpos=$(window).scrollTop(); 
			if(scrollpos >=navoffeset){
				$(".agileits_header").addClass("fixed");
			}else{
				$(".agileits_header").removeClass("fixed");
			}
		 });
		 
	});
	</script>
<!-- //script-for sticky-nav -->
	<div class="logo_products">
		<div class="container">
			<div class="w3ls_logo_products_left">
				<h1><a href="{% url 'product:home' %}"><span>Grocery</span> Store</a></h1>
			</div>
			<div class="w3ls_logo_products_left1">
				<ul class="special_items">
					<li><a href="events.html">Events</a><i>/</i></li>
					<li><a href="{% url 'product:about' %}">About Us</a><i>/</i></li>
					<li><a href="{% url 'product:product' %}">Best Deals</a><i>/</i></li>
					<li><a href="{% url 'product:restric' %}">enter your product</a><i>/</i></li>
				</ul>
			</div>
			<div class="w3ls_logo_products_left1">
				<ul class="phone_email">
					<li><i class="fa fa-phone" aria-hidden="true"></i>(+0123) 234 567</li>
					<li><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="mailto:store@grocery.com">store@grocery.com</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>

		<div class="w3l_banner_nav_left">
		<nav class="navbar nav_bottom">
		 <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header nav_2">
			  <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
		   </div> 
		   <!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
				<ul class="nav nabar-nav nav_1">
					<li><a href="{% url 'product:product' %}">All Products</a></li>
					{% for category in categorylist %}
					<li><a href="{% url 'product:categorydetail' category.id %}">{{category.title}}</a></li>
					{% endfor %}
				</ul>
			 </div><!-- /.navbar-collapse -->
		</nav>
	</div>

{% block content %}


{% endblock %}

<!-- banner -->

<!-- //newsletter -->
<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="col-md-3 w3_footer_grid">
				<h3>information</h3>
				<ul class="w3_footer_grid_list">
					<li><a href="events.html">Events</a></li>
					<li><a href="{% url 'product:about' %}">About Us</a></li>
					<li><a href="services.html">Services</a></li>
					<li><a href="short-codes.html">Short Codes</a></li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>policy info</h3>
				<ul class="w3_footer_grid_list">
					<li><a href="faqs.html">FAQ</a></li>
					<li><a href="privacy.html">privacy policy</a></li>
					<li><a href="privacy.html">terms of use</a></li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>what in stores</h3>
				<ul class="w3_footer_grid_list">
					<li><a href="pet.html">Pet Food</a></li>
					<li><a href="frozen.html">Frozen Snacks</a></li>
					<li><a href="{% url 'product:kitchen' %}">Kitchen</a></li>
					<li><a href="{% url 'product:product' %}">Branded Foods</a></li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>twitter posts</h3>
				<ul class="w3_footer_grid_list1">
					<li><label class="fa fa-twitter" aria-hidden="true"></label><i>01 day ago</i><span>Non numquam <a href="#">http://sd.ds/13jklf#</a>
						eius modi tempora incidunt ut labore et
						<a href="#">http://sd.ds/1389kjklf#</a>quo nulla.</span></li>
					<li><label class="fa fa-twitter" aria-hidden="true"></label><i>02 day ago</i><span>Con numquam <a href="#">http://fd.uf/56hfg#</a>
						eius modi tempora incidunt ut labore et
						<a href="#">http://fd.uf/56hfg#</a>quo nulla.</span></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
			<div class="agile_footer_grids">
				<div class="col-md-3 w3_footer_grid agile_footer_grids_w3_footer">
					<div class="w3_footer_grid_bottom">
						<h4>100% secure payments</h4>
						<img src="{% static 'images/card.png' %}" alt=" " class="img-responsive" />
					</div>
				</div>
				<div class="col-md-3 w3_footer_grid agile_footer_grids_w3_footer">
					<div class="w3_footer_grid_bottom">
						<h5>connect with us</h5>
						<ul class="agileits_social_icons">
							<li><a href="#" class="facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
							<li><a href="#" class="twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							<li><a href="#" class="google"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
							<li><a href="#" class="instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
							<li><a href="#" class="dribbble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="wthree_footer_copy">
				<p>© 2016 Grocery Store. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
			</div>
		</div>
	</div>
<!-- //footer -->
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>
<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
<!-- //here ends scrolling icon -->
<script src="{% static 'js/minicart.js' %}"></script>
<script>
		paypal.minicart.render();

		paypal.minicart.cart.on('checkout', function (evt) {
			var items = this.items(),
				len = items.length,
				total = 0,
				i;

			// Count the number of each item in the cart
			for (i = 0; i < len; i++) {
				total += items[i].get('quantity');
			}

			if (total < 3) {
				alert('The minimum order quantity is 3. Please add more to your shopping cart before checking out');
				evt.preventDefault();
			}
		});

	</script>
	<!--Start of Tawk.to Script-->
	<script type="text/javascript">
	var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
	(function(){
	var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
	s1.async=true;
	s1.src='https://embed.tawk.to/5d43ded17d27204601c8e4ba/default';
	s1.charset='UTF-8';
	s1.setAttribute('crossorigin','*');
	s0.parentNode.insertBefore(s1,s0);
	})();
	</script>
	<!--End of Tawk.to Script-->
</body>
</html>

templates/create.html
{% extends "base.html" %}
{% block content %}
<div class="banner">
<div class="w3l_banner_nav_right">
<div class="w3_login">
	<h3>enter the product details</h3>
	<form method="POST" enctype="multipart/form-data">
		<div class="w3_login_module">
			<div class="module form-module">
			  <div class="toggle"><i class="fa fa-times fa-pencil"></i>
				<div class="tooltip">Click Me</div>
			  </div>
			  <div class="form">	
			     {% csrf_token %}
			     <br>
		         {{form.as_p}}
		        <button>submit</button>
		      </div>
		    </div>
		</div>
	</form>


{% endblock %}

templates/households.html
{% extends "base.html" %}
<br><br><br>
{% load static %}
{% block content %}

<!-- products-breadcrumb -->

<!-- //products-breadcrumb -->
<!-- banner -->
	<div class="banner">

		<div class="w3l_banner_nav_right">
			<div class="w3l_banner_nav_right_banner4" style="background:url({{categoryobject.image.url}}) no-repeat 0px 0px;">
				<h3>Best Deals For New Products<span class="blink_me"></span></h3>
			</div>
			<div class="w3ls_w3l_banner_nav_right_grid w3ls_w3l_banner_nav_right_grid_sub">
				
				<h3>{{ categoryobject.title }} Products</h3>
						{% for subcategory in categoryobject.sub_category_set.all %}
				<div class="w3ls_w3l_banner_nav_right_grid1">
					<h6>{{subcategory.title}}</h6>
					{% for i in subcategory.product_set.all %}	
						<div class="col-md-3 w3ls_w3l_banner_left">
							<div class="hover14 column">
							<div class="agile_top_brand_left_grid w3l_agile_top_brand_left_grid">
								<div class="agile_top_brand_left_grid_pos">
									<img src="{% static 'images/offer.png' %}" alt=" " class="img-responsive"/>
								</div>
								<div class="agile_top_brand_left_grid1">
									<figure>
										<div class="snipcart-item block">
											<div class="snipcart-thumb">
												<a href="/product/{{i.id}}/details/">><img src="{{ i.images.url }}" style="height:250px;object-fit: cover" class="img-responsive" /></a>
												<p>{{ i.name }}</p>
												<h4>{{ i.price }}({{i.weight }}{{ i.quentity }})</h4>
												<p>views{{ i.view_count }}</p>
											</div>
											<div class="snipcart-details">
												<form action="#" method="post">
													<fieldset>
														<input type="hidden" name="cmd" value="_cart" />
														<input type="hidden" name="add" value="1" />
														<input type="hidden" name="business" value=" " />
														<input type="hidden" name="item_name" value="dishwash gel, lemon" />
														<input type="hidden" name="amount" value="8.00" />
														<input type="hidden" name="discount_amount" value="1.00" />
														<input type="hidden" name="currency_code" value="USD" />
														<input type="hidden" name="return" value=" " />
														<input type="hidden" name="cancel_return" value=" " />
														<input type="submit" name="submit" value="Add to cart" class="button" />
													</fieldset>
												</form>
											</div>
										</div>
									</figure>
								</div>
							</div>
							</div>
						</div>
					{% empty %}
					<h4>No products found...</h4>
				{% endfor %}
					<div class="clearfix"> </div>
				</div>
			{% endfor %}
		
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
<!-- //banner -->
<!-- newsletter -->
	<div class="newsletter">
		<div class="container">
			<div class="w3agile_newsletter_left">
				<h3>sign up for our newsletter</h3>
			</div>
			<div class="w3agile_newsletter_right">
				<form action="#" method="post">
					<input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<input type="submit" value="subscribe now">
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>

{% endblock %}

templates/practise.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- products-breadcrumb -->

<!-- //products-breadcrumb -->
<!-- banner -->
	<div class="banner">

		<div class="w3l_banner_nav_right">
			<div class="w3l_banner_nav_right_banner4" style="background:url({{categoryobject.image.url}}) no-repeat 0px 0px;">
				<h3>Best Deals For New Products<span class="blink_me"></span></h3>
			</div>
			<div class="w3ls_w3l_banner_nav_right_grid w3ls_w3l_banner_nav_right_grid_sub">
				
				<h3>{{ categoryobject.title }} Products</h3>
						{% for subcategory in categoryobject.sub_category_set.all %}
				<div class="w3ls_w3l_banner_nav_right_grid1">
					<h6>{{subcategory.title}}</h6>
					{% for i in subcategory.product_set.all %}	
						<div class="col-md-3 w3ls_w3l_banner_left">
							<div class="hover14 column">
							<div class="agile_top_brand_left_grid w3l_agile_top_brand_left_grid">
								<div class="agile_top_brand_left_grid_pos">
									<img src="{% static 'images/offer.png' %}" alt=" " class="img-responsive"/>
								</div>
								<div class="agile_top_brand_left_grid1">
									<figure>
										<div class="snipcart-item block">
											<div class="snipcart-thumb">
												<a href="single.html"><img src="{{ i.images.url }}" style="height:250px;object-fit: cover" class="img-responsive" /></a>
												<p>{{ i.name }}</p>
												<h4>{{ i.price }}</h4>
											</div>
											<div class="snipcart-details">
												<form action="#" method="post">
													<fieldset>
														<input type="hidden" name="cmd" value="_cart" />
														<input type="hidden" name="add" value="1" />
														<input type="hidden" name="business" value=" " />
														<input type="hidden" name="item_name" value="dishwash gel, lemon" />
														<input type="hidden" name="amount" value="8.00" />
														<input type="hidden" name="discount_amount" value="1.00" />
														<input type="hidden" name="currency_code" value="USD" />
														<input type="hidden" name="return" value=" " />
														<input type="hidden" name="cancel_return" value=" " />
														<input type="submit" name="submit" value="Add to cart" class="button" />
													</fieldset>
												</form>
											</div>
										</div>
									</figure>
								</div>
							</div>
							</div>
						</div>
					{% empty %}
					<h4>No products found...</h4>
				{% endfor %}
					<div class="clearfix"> </div>
				</div>
			{% endfor %}
		
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
<!-- //banner -->
<!-- newsletter -->
	<div class="newsletter">
		<div class="container">
			<div class="w3agile_newsletter_left">
				<h3>sign up for our newsletter</h3>
			</div>
			<div class="w3agile_newsletter_right">
				<form action="#" method="post">
					<input type="email" name="Email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
					<input type="submit" value="subscribe now">
				</form>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>

{% endblock %}

templates/single.html
{% extends "base.html" %}
{% load static %}
{% block single %}
	
{% endblock %}